version: "3.9"
services:
  finskubot:
    build:
      context: .
    image: finskubot
    container_name: finskubot
    deploy:
      restart_policy: 
        condition: on-failure
        max_attempts: 3
    command: npm run start
    environment:
      - NODE_ENV=production
      # Token from Discord Developers Portal
      - BOT_TOKEN=TOKEN
      # Token which bot uses (!command)
      - BOT_PREFIX=!
      # User ID who can use 'admin' commands
      - BOT_OWNER=ID
      # Server where bot works
      - BOT_HOMESERVER=ID
      # Channel where bot sends logs/info
      - BOT_HOMECHANNEL=ID
